name: Frontend CD Pipeline

on:
  workflow_run:
    workflows: ["Frontend CI Pipeline"]
    types:
      - completed
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    name: Package and Publish to GHCR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # git writeback
      - name: Checkout DevOps Infra Repo
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/devops-infra'
          token: ${{ secrets.INFRA_REPO_PAT }}
          path: devops-infra

      - name: Update Image Tag in Manifest
        run: |
          # Matches the 'type=sha,format=long' tag convention generated by docker/metadata-action
          TARGET_TAG="sha-${{ github.event.workflow_run.head_sha }}"
          
          cd devops-infra/kubernetes/platform/frontend
          
          # Safely substitute the old tag (whether it was :latest or an old sha) with the new immutable tag
          sed -i "s|image: ghcr.io/ishehov-devops-practice/frontend-react:.*|image: ghcr.io/ishehov-devops-practice/frontend-react:${TARGET_TAG}|g" deployment.yml

      - name: Commit and Push Changes to Infra Repo
        run: |
          cd devops-infra
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add kubernetes/platform/frontend/deployment.yml
          
          # Only commit and push if changes are present (prevents pipeline crashes on manual workflow re-runs)
          if ! git diff --cached --quiet; then
            git commit -m "chore(gitops): automated frontend rollout to sha-${{ github.event.workflow_run.head_sha }}"
            git push origin main
          else
            echo "No changes detected. Manifest is already up to date."
          fi